### PR TITLE
Updated for Bluetooth Arsenal

### PR DESCRIPTION
**Pull request by yesimxev**

### CODE REVIEW

**Comment by Shubhamvis98** [comment]
hi,
need help in adding mt7601u driver
i compiled the module and enabled it but the wifi interface is not showing in `ifconfig -a` or `iwconfig`
only showing in `lsusb`
also checked `dmesg` log, it shows that new interface is registered but the interface is not showing
i also tried `ifconfig wlan1 up`, `ifconfig ra0 up` , etc but no success
please help...

**Comment by yesimxev** [comment]
@Shubhamvis98 This is more like a forum question. Anyway, if you enabled as module then you should modprobe it. Btw, is it showing if using a driver in `lsusb -t`?

**Comment by Shubhamvis98** [comment]
> @Shubhamvis98 This is more like a forum question. Anyway, if you enabled as module then you should modprobe it. Btw, is it showing if using a driver in `lsusb -t`?

not showing the driver in `lsusb -t`
when i run `strings mt7601u.ko | grep bin` i didn't get the firmware file

**Comment by Shubhamvis98** [comment]
i have also this issue
i replaced the screen, now i cant use any custom rom
now Oxygen OS installed (pie)
when i flash nethunter kernel or lineage os, or any other custom os then the phone won't wake after screen lock
when i use screen share programs like `scrcpy` then the screen is showing on the program
but phone's screen is flickering
i tried replacing display drivers from OOS kernel to the nethunter-9.0 kernel but not working
do you have any suggestion

the dmesg log of nethunter kernel:
a
b
c
d
e
f
g

Screenshot_20201003-215057

**Comment by DroidKali** [comment]
compile errors
```
  CC      drivers/staging/prima/CORE/MAC/src/pe/lim/limAdmitControl.o
  CC      drivers/staging/prima/CORE/MAC/src/pe/lim/limApi.o
  CC      drivers/usb/gadget/function/f_hid.o
../drivers/net/wireless/rtl8812au/os_dep/linux/ioctl_cfg80211.c: In function 'cfg80211_rtw_get_station':
../drivers/net/wireless/rtl8812au/os_dep/linux/ioctl_cfg80211.c:2332:28: error: 'STATION_INFO_BSS_PARAM_SHORT_PREAMBLE' undeclared (first use in this function)
  sinfo->bss_param.flags |= STATION_INFO_BSS_PARAM_SHORT_PREAMBLE;
                            ^
../drivers/net/wireless/rtl8812au/os_dep/linux/ioctl_cfg80211.c:2332:28: note: each undeclared identifier is reported only once for each function it appears in
../drivers/net/wireless/rtl8812au/os_dep/linux/ioctl_cfg80211.c:2335:30: error: 'STATION_INFO_BSS_PARAM_SHORT_SLOT_TIME' undeclared (first use in this function)
    sinfo->bss_param.flags |= STATION_INFO_BSS_PARAM_SHORT_SLOT_TIME;
                              ^
../drivers/net/wireless/rtl8812au/os_dep/linux/ioctl_cfg80211.c:2339:28: error: 'STATION_INFO_BSS_PARAM_CTS_PROT' undeclared (first use in this function)
  sinfo->bss_param.flags |= STATION_INFO_BSS_PARAM_CTS_PROT;
                            ^
../drivers/net/wireless/rtl8812au/os_dep/linux/ioctl_cfg80211.c:2342:28: error: 'STATION_INFO_BSS_PARAM_DTIM_PERIOD' undeclared (first use in this function)
  sinfo->bss_param.flags |= STATION_INFO_BSS_PARAM_DTIM_PERIOD;
                            ^
../drivers/net/wireless/rtl8812au/os_dep/linux/ioctl_cfg80211.c: At top level:
../drivers/net/wireless/rtl8812au/os_dep/linux/ioctl_cfg80211.c:10008:2: warning: initialization from incompatible pointer type
  .del_station = cfg80211_rtw_del_station,
  ^
../drivers/net/wireless/rtl8812au/os_dep/linux/ioctl_cfg80211.c:10008:2: warning: (near initialization for 'rtw_cfg80211_ops.del_station')
make[5]: *** [../scripts/Makefile.build:265: drivers/net/wireless/rtl8812au/os_dep/linux/ioctl_cfg80211.o] Error 1
make[5]: *** Waiting for unfinished jobs....
  LD      drivers/usb/gadget/function/usb_f_acm.o
  CC      drivers/video/fbdev/msm/../../msm/mdss/mdss_dsi.o
  CC      drivers/video/fbdev/msm/../../msm/mdss/mdss_dsi_host.o
  CC      drivers/usb/mon/mon_text.o
  LD      drivers/usb/gadget/function/usb_f_serial.o
  LD      drivers/usb/gadget/function/usb_f_ncm.o
  LD      drivers/usb/gadget/function/usb_f_ecm.o
  CC      drivers/staging/prima/CORE/MAC/src/pe/lim/limAssocUtils.o
  LD      drivers/usb/gadget/function/usb_f_mass_storage.o
  CC      drivers/video/fbdev/msm/../../msm/mdss/mdss_dsi_cmd.o
  LD      drivers/usb/gadget/function/usb_f_fs.o
  CC      drivers/usb/mon/mon_bin.o
  LD      drivers/usb/gadget/function/usb_f_uac1.o
  LD      drivers/usb/gadget/function/usb_f_uac2.o
  LD      drivers/usb/gadget/function/usb_f_uvc.o
  LD      drivers/usb/gadget/function/usb_f_audio_source.o
  LD      drivers/usb/gadget/function/usb_f_hid.o
  LD      drivers/usb/gadget/function/built-in.o
  CC      drivers/staging/prima/CORE/MAC/src/pe/lim/limDebug.o
  CC      drivers/video/fbdev/msm/../../msm/mdss/mdss_dsi_status.o
  CC      drivers/usb/gadget/udc/udc-core.o
  LD      drivers/usb/mon/usbmon.o
  LD      drivers/usb/mon/built-in.o
  CC      drivers/usb/phy/phy.o
  CC      drivers/video/fbdev/msm/../../msm/mdss/mdss_dsi_panel.o
  CC      drivers/staging/prima/CORE/MAC/src/pe/lim/limFT.o
  CC      drivers/staging/prima/CORE/MAC/src/pe/lim/limIbssPeerMgmt.o
  LD      drivers/usb/gadget/udc/built-in.o
  CC      drivers/usb/gadget/android.o
  CC      drivers/usb/phy/of.o
  CC      drivers/video/fbdev/msm/../../msm/mdss/msm_mdss_io_8974.o
  CC      drivers/usb/phy/class-dual-role.o
  CC      drivers/staging/prima/CORE/MAC/src/pe/lim/limLinkMonitoringAlgo.o
  CC      drivers/usb/phy/phy-generic.o
  CC      drivers/staging/prima/CORE/MAC/src/pe/lim/limLogDump.o
  CC      drivers/staging/prima/CORE/MAC/src/pe/lim/limP2P.o
  CC      drivers/video/fbdev/msm/../../msm/mdss/mdss_dsi_phy.o
  CC      drivers/usb/phy/phy-msm-usb.o
  CC      drivers/staging/prima/CORE/MAC/src/pe/lim/limProcessActionFrame.o
  CC      drivers/usb/gadget/ci13xxx_msm.o
  CC      drivers/usb/phy/phy-msm-hsusb.o
  CC      drivers/video/fbdev/msm/../../msm/mdss/mdss_dsi_clk.o
  CC      drivers/staging/prima/CORE/MAC/src/pe/lim/limProcessAssocReqFrame.o
  CC      drivers/usb/phy/phy-msm-ssusb-qmp.o
  CC      drivers/usb/phy/phy-msm-qusb.o
make[4]: *** [../scripts/Makefile.build:410: drivers/net/wireless/rtl8812au] Error 2
make[3]: *** [../scripts/Makefile.build:410: drivers/net/wireless] Error 2
make[2]: *** [../scripts/Makefile.build:410: drivers/net] Error 2
make[2]: *** Waiting for unfinished jobs....
```

**Pull request merged**
